#ifndef _LCOM_I8042_H_
#define _LCOM_I8042_H_

#define IRQ_KEYBOARD 1
#define IRQ_MOUSE 12
#define KEYBOARD_IRQ_SET BIT(1)
#define MOUSE_IRQ_SET BIT(2)

#define BRK_ESC 0x81
#define TWO_BYTE_SCANCODE 0xE0

#define TIMEOUT_ERROR BIT(6)
#define PARITY_ERROR BIT(7)
#define MOUSE BIT(5)
#define IN_BUFFER_FULL BIT(1)
#define OUT_BUFFER_FULL BIT(0)

#define KBC_OUT_BUF 0x60
#define KBC_WRITE_CMD_BYTE 0x60
#define KBC_STATUS_REGISTER 0x64
#define KBC_IN_BUFFER 0x64
#define KBC_READ_CMD 0x20

#define DELAY_US    20000

#define MOUSE_LEFT_BUTTON BIT(0)
#define MOUSE_RIGHT_BUTTON BIT(1)
#define MOUSE_MIDDLE_BUTTON BIT(2)
#define MOUSE_3_BIT BIT(3)
#define MOUSE_X_DISPLACEMENT BIT(4)
#define MOUSE_Y_DISPLACEMENT BIT(5)
#define MOUSE_X_OVERFLOW BIT(6)
#define MOUSE_Y_OVERFLOW BIT(7)

#define ENTER_BRK 0x9C
#define SPACE_BRK 0xB9
#define F_BRK 0xA1
#define ARROW_UP_BRK 0xC8
#define ARROW_DOWN_BRK 0xD0
#define ARROW_LEFT_BRK 0xCB
#define ARROW_RIGHT_BRK 0xCD
#define ARROW_UP_MAKE 0x48
#define ARROW_DOWN_MAKE 0x50
#define ARROW_RIGHT_MAKE 0x4d
#define ARROW_LEFT_MAKE 0x4b

#define DISABLE_MOUSE 0xA7
#define ENABLE_MOUSE 0xA8
#define CHECK_MOUSE_INTERFACE 0xA9
#define WRITE_BYTE_MOUSE 0xD4
#define ENABLE_DATA_REPORTING 0xF4
#define DISABLE_DATA_REPORTING 0xF5
#define ACK 0xFA
#endif /* _LCOM_I8042_H_ */
